export { 
    InfoCircleFill,
    InfoCircleOutline,
    InfoCircleTwoTone,
    CheckCircleFill,
    CheckCircleOutline,
    CheckCircleTwoTone,
    CloseCircleFill,
    CloseCircleOutline,
    CloseCircleTwoTone,
    ExclamationCircleFill,
    ExclamationCircleOutline,
    LoadingOutline,
    Loading3QuartersOutline,
    SelectOutline,
    ArrowLeftOutline,
    DownOutline,
    LeftOutline,
    RightOutline
} from '@ant-design/icons'
